// Generates the two consumable forms from src/: a Tailwind preset for projects
// that have Tailwind, and plain CSS classes for the ones that don't (Vue, Astro,
// anything without a Tailwind build). Same class names either way, so markup
// copied between projects keeps working.
import { mkdirSync, copyFileSync, writeFileSync } from 'node:fs'
import { readFile } from 'node:fs/promises'

const read = async (name) => JSON.parse(await readFile(new URL(`src/${name}`, import.meta.url), 'utf8'))
const [type, theme, meta] = await Promise.all([read('type.json'), read('theme.json'), read('meta.json')])

mkdirSync(new URL('dist/', import.meta.url), { recursive: true })

const lines = [
  '@plivo/tokens — generated by build.mjs, do not edit.',
  `Extracted from Plivo's design system on ${meta.extractedAt}.`,
]
const cssBanner = `/* ${lines.join('\n   ')} */`
const jsBanner = lines.map((l) => `// ${l}`).join('\n')

/** Tailwind wants [size, { lineHeight, fontWeight, ... }]; family and transform
    have no home in that tuple, so they only survive into the CSS build. */
const fontSize = Object.fromEntries(
  Object.entries(type).map(([name, t]) => [
    name,
    [
      t.size,
      {
        lineHeight: t.line,
        fontWeight: String(t.weight),
        ...(t.tracking ? { letterSpacing: t.tracking } : {}),
        ...(t.style ? { fontStyle: t.style } : {}),
      },
    ],
  ])
)

writeFileSync(
  new URL('dist/tailwind.cjs', import.meta.url),
  `${jsBanner}
module.exports = {
  theme: {
    extend: ${JSON.stringify({ colors: theme.colors, borderRadius: theme.borderRadius, fontFamily: theme.fontFamily, fontSize }, null, 6).replace(/\n/g, '\n    ')},
  },
}
`
)

// A family name with a space must be quoted in CSS; the source arrays are bare.
const stack = (key) =>
  theme.fontFamily[key]?.map((f) => (/\s/.test(f) ? `'${f}'` : f)).join(', ')
const rule = (name, t) =>
  [
    `.text-${name} {`,
    `  font-size: ${t.size};`,
    `  line-height: ${t.line};`,
    `  font-weight: ${t.weight};`,
    t.tracking && `  letter-spacing: ${t.tracking};`,
    t.style && `  font-style: ${t.style};`,
    `  font-family: ${familyVar(name, t)};`,
    t.transform && `  text-transform: ${t.transform};`,
    '}',
  ]
    .filter(Boolean)
    .join('\n')

/* The class form only helps consumers that control the markup. A library
   styling its own elements needs custom properties, so emit both: a `font`
   shorthand per token (weight size/line family) plus tracking, which the
   shorthand cannot carry. */
// Family is chosen by role, not repeated per token: Sora for display sizes,
// JetBrains Mono for the label/eyebrow, Inter for everything else. Each goes
// through its own var so a host can swap a face without touching the ramp.
const familyVar = (name, t) => {
  if (t.family === 'jetbrains') return 'var(--font-mono, ui-monospace, monospace)'
  if (/^(h[1-4]|xl)-/.test(name)) return 'var(--font-display, var(--font-sans, system-ui, sans-serif))'
  return 'var(--font-sans, system-ui, sans-serif)'
}

const fontVar = (name, t) =>
  `  --text-${name}: ${t.style ? `${t.style} ` : ''}${t.weight} ${t.size}/${t.line} ${familyVar(
    name,
    t
  )};${t.tracking ? `\n  --text-${name}-tracking: ${t.tracking};` : ''}`

const familyVars = [
  `  --font-sans: ${stack('inter')};`,
  `  --font-display: ${stack('sora')};`,
  `  --font-mono: ${stack('jetbrains')};`,
].join('\n')

writeFileSync(
  new URL('dist/type.css', import.meta.url),
  `${cssBanner}

:root {
${familyVars}

${Object.entries(type).map(([n, t]) => fontVar(n, t)).join('\n')}
}

${Object.entries(type).map(([n, t]) => rule(n, t)).join('\n\n')}
`
)

copyFileSync(new URL('src/colors.css', import.meta.url), new URL('dist/colors.css', import.meta.url))
copyFileSync(new URL('src/type.json', import.meta.url), new URL('dist/type.json', import.meta.url))

console.log(`built ${Object.keys(type).length} type classes + ${Object.keys(theme.colors).length} colour groups`)
