// One-way extraction from the internal console checkout into this package's
// sources. Re-runnable: when the upstream theme branch moves, point this at the
// new ref and diff the result. Upstream stays the source of truth until it
// consumes @plivo/tokens instead.
//
// The repo path and ref are arguments, never committed — generated files record
// only the date, so a public package does not advertise private repo names.
import { execFileSync } from 'node:child_process'
import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const [repo, ref = 'origin/main'] = process.argv.slice(2)
if (!repo) {
  console.error('usage: node scripts/extract.mjs <console-repo-path> [git-ref]')
  process.exit(1)
}

const show = (path) =>
  execFileSync('git', ['-C', repo, 'show', `${ref}:${path}`], { encoding: 'utf8', maxBuffer: 1 << 24 })

const scratch = mkdtempSync(join(tmpdir(), 'plivo-tokens-'))

// tailwind.base.js is CommonJS, so require it rather than parsing it — the theme
// object is already the data we want, and a regex would rot on the next edit.
writeFileSync(join(scratch, 'tailwind.base.cjs'), show('tailwind.base.js'))

// The config `require()`s its Tailwind plugins, which aren't dependencies here.
// Stub anything unresolvable so the theme object still loads — regex-stripping
// the plugins array would rot on the next upstream edit.
const shim = join(scratch, 'load.cjs')
writeFileSync(
  shim,
  `const Module = require('module')
const load = Module._load
Module._load = function (request, ...rest) {
  try {
    return load.call(this, request, ...rest)
  } catch {
    return () => {}
  }
}
module.exports = require('./tailwind.base.cjs')
`
)
const { theme } = (await import(`file://${shim}`)).default

/** Tailwind's fontSize tuple can't carry family or text-transform, so widen it. */
const type = Object.fromEntries(
  Object.entries(theme.extend.fontSize).map(([name, [size, meta]]) => [
    name,
    {
      size,
      line: meta.lineHeight,
      weight: Number(meta.fontWeight ?? 400),
      ...(meta.letterSpacing ? { tracking: meta.letterSpacing } : {}),
      ...(meta.fontStyle ? { style: meta.fontStyle } : {}),
    },
  ])
)

// `label` is mono + uppercase by design, but a Tailwind fontSize tuple cannot say
// so — upstream applies `font-jetbrains uppercase` at every call site. Record it
// here so the generated CSS class carries it and callers stop repeating it.
if (type.label) Object.assign(type.label, { family: 'jetbrains', transform: 'uppercase' })

/** Pull `--name: value;` declarations out of a scss block, preserving order. */
const varsIn = (scss, open) => {
  const start = scss.indexOf(open)
  if (start === -1) return []
  let depth = 0
  let i = scss.indexOf('{', start)
  const from = i + 1
  for (; i < scss.length; i++) {
    if (scss[i] === '{') depth++
    else if (scss[i] === '}' && --depth === 0) break
  }
  return [...scss.slice(from, i).matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)].map((m) => [
    m[1],
    m[2].trim(),
  ])
}

// Tailwind's semantic colour mapping (name -> hsl(var(--token))). `flow` is the
// CX flow-builder's own palette, not brand — it stays in the product.
const PRODUCT_ONLY = new Set(['flow'])
const colors = Object.fromEntries(
  Object.entries(theme.extend.colors).filter(([name]) => !PRODUCT_ONLY.has(name))
)

const main = show('packages/neo/src/style/main.scss')
const legacy = show('packages/neo/src/style/variables.scss')
const light = [...varsIn(legacy, ':root'), ...varsIn(main, ':root')]
const dark = varsIn(main, '.dark')

const block = (selector, pairs) =>
  `${selector} {\n${pairs.map(([k, v]) => `  ${k}: ${v};`).join('\n')}\n}`

const css = `/* Generated by scripts/extract.mjs — do not edit by hand.
   Extracted from Plivo's internal design system. */

${block(':root', light)}

${block('.dark', dark)}
`

writeFileSync(new URL('../src/colors.css', import.meta.url), css)
writeFileSync(
  new URL('../src/type.json', import.meta.url),
  `${JSON.stringify(type, null, 2)}\n`
)
writeFileSync(
  new URL('../src/theme.json', import.meta.url),
  `${JSON.stringify({ colors, borderRadius: theme.extend.borderRadius, fontFamily: theme.extend.fontFamily }, null, 2)}\n`
)
writeFileSync(
  new URL('../src/meta.json', import.meta.url),
  `${JSON.stringify({ extractedAt: new Date().toISOString().slice(0, 10) }, null, 2)}\n`
)

console.log(
  `extracted ${Object.keys(type).length} type tokens, ${Object.keys(colors).length} colour groups, ${light.length} light vars, ${dark.length} dark vars`
)
